// Generated by SolidPython 0.4.6 on 2020-02-04 22:27:55


cube(size = [10, 20, 20]);
/***********************************************
*********      SolidPython code:      **********
************************************************
 
from solid import *


thermostat_case = cube([10,20,20])

scad_render_to_file(thermostat_case, 'models\\thermostat_case.scad') 
 
************************************************/
